experiment_name: test
dataset:
  images_path: ../data/train/images
  image_ids: ../data/train/img_list.txt
  gt_path: ../data/train/gt
  gt_ids: ../data/train/gt_list.txt
  input_size: 128
  img_convert: RGB
  gt_convert: L
model:
  model_name: UNet
  in_channel: 1
  n_classes: 1
logs:
  use_wandb: True
  log_history_path: ../logs/test/history
  log_out_path: ../logs/test/out
test_setup:
  checkpoints_path: ../checkpoints
  batch_size: 1
  device: gpu
  device_ids: 0
  dataparallel: False
  model_weight_load: True
  model_weight_path: 2019-09-17 12:22:27.449158_epoch-3_dice-0.1.pth
