experiment_name: train
dataset:
  image_path: /media/sadi/Vol_2/US/DSPRL-Ultrasoundseg/data/data_for_pipeline_check/test/images
  label_path: /media/sadi/Vol_2/US/DSPRL-Ultrasoundseg/data/data_for_pipeline_check/test/labels
  train_image_ids: /media/sadi/Vol_2/general_code_reps/pytorchPipeline/dataloaders/dataset_split0/train_img_ids.txt
  train_label_ids: /media/sadi/Vol_2/general_code_reps/pytorchPipeline/dataloaders/dataset_split0/train_label_ids.txt
  val_image_ids: /media/sadi/Vol_2/general_code_reps/pytorchPipeline/dataloaders/dataset_split0/val_img_ids.txt
  val_label_ids: /media/sadi/Vol_2/general_code_reps/pytorchPipeline/dataloaders/dataset_split0/val_label_ids.txt
  train_ratio: 0.8
  input_size: 128
  img_convert: RGB
  label_convert: L
model:
  model_name: UNet
  pretrained: False
  pretrain_weight:
  in_channel: 3
  n_classes: 1
  dataparallel: False
optimizer:
  optimizer_fn: Adam
  initial_lr: 0.0001
logs:
  use_wandb: False
  wandb_project_name: pytorchPipeline
  wandb_entity: sadimohammad
  run_name:
  save_local_logs: True
  save_local_config: True
  local_logs_path: /media/sadi/Vol_2/general_code_reps/pytorchPipeline/logs/out
  local_cfgs_path: /media/sadi/Vol_2/general_code_reps/pytorchPipeline/logs/cfgs
train_setup:
  checkpoints_path: /media/sadi/Vol_2/general_code_reps/pytorchPipeline/ckpts
  batch_size: 10
  epochs: 20
  device: cuda:0
  device_ids: 0
  dataparallel: False
  model_weight_load: False
  best_valid_score: 0.0
  model_weight_path: 2019-09-17 12:22:27.449158_epoch-3_dice-0.0.pth
  loss: dice_coeff_loss
  metric: iou_calc
  use_thld_for_valid: True #threshold for validation
  thld_for_valid: 0.5 #threshold for validation
  save_best_model: False
