experiment_name: train
dataset:
  image_path: "/media/sadi/Vol_2/US/DSPRL-Ultrasoundseg/data/data_for_pipeline_check/test/images"
  image_ids: "/media/sadi/Vol_2/US/DSPRL-Ultrasoundseg/data/data_for_pipeline_check/test/img_list.txt"
  gt_path: "/media/sadi/Vol_2/US/DSPRL-Ultrasoundseg/data/data_for_pipeline_check/test/gt"
  gt_ids: "/media/sadi/Vol_2/US/DSPRL-Ultrasoundseg/data/data_for_pipeline_check/test/gt_list.txt"
  train_ratio: 0.8
  input_size: 128
  img_convert: L
  gt_convert: L
model:
  model_name: deeplabv3
  pretrained: False
  pretrain_weight:
  in_channel: 3
  n_classes: 1
  dataparallel: False
optimizer:
  optimizer_fn: Adam
  initial_lr: 0.0001
logs:
  use_wandb: True
  log_history_path: ../logs/train/history
  log_out_path: ../logs/train/out
train_setup:
  checkpoints_path: ../ckpts
  batch_size: 10
  epochs: 20
  device: gpu
  device_ids: 0
  dataparallel: False
  model_weight_load: False
  best_valid_score: 0.0
  model_weight_path: 2019-09-17 12:22:27.449158_epoch-3_dice-0.0.pth
  loss: bce
  metric: mIoU
  use_thld_for_valid: True #threshold for validation
  thld_for_valid: 0.5 #threshold for validation
  save_best_model: True
